_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.2
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": darwin-arm64
config:
    value:
        Atari_eval_frequency: 100000
        Atari_tot_timesteps: 2500000
        Dmc_eval_frequency: 5000
        Dmc_tot_timesteps: 500000
        Gym_eval_frequency: 5000
        Gym_tot_timesteps: 1000000
device:
    value: cpu
env:
    value: Gym-Ant-v4
env_type:
    value: Gym
eval_eps:
    value: 10
eval_folder:
    value: ./evals
eval_frequency:
    value: 5000
load_experiment:
    value: false
project_name:
    value: MRQ+Gym-Ant-v4+0
save_experiment:
    value: false
save_folder:
    value: ./checkpoint
save_freq:
    value: 100000
seed:
    value: 0
tot_timesteps:
    value: 20000
