wandb_version: 1

env:
  desc: null
  value: Gym-Ant-v4
seed:
  desc: null
  value: 0
total_timesteps:
  desc: null
  value: 20000
device:
  desc: null
  value: cpu
eval_frequency:
  desc: null
  value: 5000
eval_eps:
  desc: null
  value: 10
project_name:
  desc: null
  value: MRQ+Gym-Ant-v4+0
eval_folder:
  desc: null
  value: ./evals
log_folder:
  desc: null
  value: ./logs
save_folder:
  desc: null
  value: ./checkpoint
save_experiment:
  desc: null
  value: false
save_freq:
  desc: null
  value: 100000
load_experiment:
  desc: null
  value: false
config:
  desc: null
  value:
    Atari_total_timesteps: 2500000
    Atari_eval_frequency: 100000
    Dmc_total_timesteps: 500000
    Dmc_eval_frequency: 5000
    Gym_total_timesteps: 1000000
    Gym_eval_frequency: 5000
env_type:
  desc: null
  value: Gym
logger:
  desc: null
  value: <utils.Logger object at 0x13eb07450>
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.17.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1745095317
    t:
      1:
      - 1
      - 55
      - 105
      2:
      - 1
      - 55
      - 105
      3:
      - 13
      - 16
      - 23
      - 61
      4: 3.11.5
      5: 0.17.9
      8:
      - 4
      - 5
      13: darwin-arm64
