wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.21
    cli_version: 0.19.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1746496174
    t:
      1:
      - 1
      - 55
      3:
      - 4
      - 13
      - 16
      - 23
      - 42
      - 55
      4: 3.9.21
      5: 0.19.9
      8:
      - 5
      13: linux-x86_64
env:
  desc: null
  value: Gym-Ant-v4
seed:
  desc: null
  value: 1
total_timesteps:
  desc: null
  value: 1000000
device:
  desc: null
  value: cpu
eval_freq:
  desc: null
  value: 5000.0
eval_eps:
  desc: null
  value: 10
path:
  desc: null
  value: logs/embeddings/Gym-Ant-v4_seed_1_zs512_za256_zsa512_timesteps1000000
zs_dim:
  desc: null
  value: 512
za_dim:
  desc: null
  value: 256
zsa_dim:
  desc: null
  value: 512
